language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  access_key_id: AKIAIK5IXECGIGW67N7A
  secret_access_key:
    secure: G1uI8gbwmjhn00mjEZOqt7w13gZRNT1fG6N7CFq5yshX7cM3hum8f3yIjxyBBpQAs3fOsvXYt41ynpvHy2toEC4xQS3QYClS4RWUROBL+31BoChpMBNgHMOxu9QmTdCS99VVTL5yQ4lsn3yRdllJzZ5uUfIVydp/vjPSmHgUhKNvqPc4k9rfNZNh6f5k6/OLtkWWD0oR1B0QJ9iNc7SgyBlC1qYeIFRG45PneYZK9MTbKuNc0nThNDAPN+HOSNOfxwMlC+Iu91XpC8Q+ph916znSQBqinnFGd0xuoanlatTjBvMYnpiABWn5P0oesxX9V4zFAQEMxp6KyLLkYwyzm8ZIL2uKUxpsMex+aKN1sOgZPLMW6fOA7Do6wK7KMFaHBvcw48HnmdlkTMqMP2DV0uHfQqbG/8HMNO7kJwxqWpV1JQjc4+Ob9RKArSjiM6zrPDFpvtHSctw/pxiXQbOPDuEsH4/FcYUD3skGM66LOxnHgEF0ZVQqGRguMrXK5OrC7jZHzidUem+v/+tc/ghDk4a1uCXFUsbiMb/ui1z1VYOY6TCZWLCzNPUja6icbDs87SNGcBZ2Fa1b6zFGTRuMRXsKX/LBK62975oVZcAG6ubYCGAP+BTF8NTW3j1I3AVx9+n4mKyRWE2dBMImdavZ0XP62hKdWImdi35wt1IeOVI=
  bucket: d2gwebui
  region: eu-central-1
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui
