language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  region: us-west-2
  bucket: d2g-webui
  access_key_id:
    secure: $access_key_id
  secret_access_key:
    secure: $secret_access_key
env:
  global:
  - secure: tu8C7FULednzTmJ29Y5XMlEqO0FubBX3bymR6Fd4pjVPguNC31Np1w6g5RLcFKtAUmXZFNN3nq+hhQCxRT9xYDFzhVhVWpjsRZYFIGfi006fkoJAxKlrn2YWejOkKwrl1z1iTJFEYNs/A8gRZMPZcUf6dIDslKHnRn+yAyIEIUzdhWGBWpJXII3OZB4ewuxKy/2LNY9UBjtsSPrWFBs9D75bUz1ixE3QrHPpcC9F5T5eRTCoVl2NFOPD5gbzCWZOOpFMLu8HN4KZd9Px/zec/WH3PloL6csYGHE/XW3CVCN4MyuIhFTwZ2V7koSj1Cp1GmjM68lNmSS3OxlUDVD4AM3FTaIO3iyPpfjCzswaHKKWPwohs0ohE+7lT2aiR7evoYpy1EIsVYkHupklpTSIvKOCIAMtJSe412mJtzk0pLp/kO9iPOYn87TmSmPw8EjA560BBEMo5EtaYg/qjtGLn83ig+SNbkV/eNDNMTKsCuMLmsx1EG1PWiywgT06K6U/Ou7YFrqdxlcwzsX2ykREGeJi3MHqG23wln1L2uNFqBYX0AVogBu4ospCnqHIKHr5/hefFpl7Fzgo57Oetq8Sv4SVIQyR03JruDjdjpEQ8vaecPClEunukzNpFO7dRQhTu6aVtjJrhPkXvbLBA+w0BPsg3NAWuNkLgg6AiqdBqR0=
  - secure: VXwr8mcTrh013ec1mJJ9zPgUEAat7Uz1x+x1LFhlqQfWEStEbq8Do4Ftgg4gKFklGHngFlzMENo9oNiaUUYG5IJYk4xXyLC5cEBTBkPjAF5L8HsWspBr+sDc+ayZjXXavMNSIwmxSjnhgPq8Fsv8+MfqQOFzusf3uv6gFJSn0r2e8uj+VcXzIThywGxT6TxppbaHJrdNVGE3mkBQXwqqomigG6uJwTmGB0AwRk9XVMzOCMngPt2rKRHWe/rIlX03rGp9tRJ/CUd4AHXPeK3BQTjJwWRKyPb3Bjgk5zAw4oBbulAxYzgmSTvcBTpeCs8vuO4Nlz3M0Ht19d/Z04f3xiyX23COBrp1Ey+lzijCXO8R57mYs1I4DwFRtrPysDSTYghBznJOBl/lVUBRuT2hsPGeaKKK43LFQtDD/8bXNcrYw/uqAkENWCBmsvv2L1/JPhw28UYMB4Uwt4fWkSkeFvOFfHH/8y7oSNrkku6Jj0QiALGeWssPwyvSKHbX2A86iBOs7EAWwppxJHU+X1FciIGj0Ub9TmKYV/td8ccqzOUY7RagqkKgahAhU8gf5X45wRWbYbtblZjI4YFknmXK0al1bwdj9WX6MSOPhJdlPDDoMNBRYbJirf+fdJ12DRDR0sUzm0SoH9mBTeadAL5m8Wy+ccMs9SlmeUv7YX/C3BY=
