language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  access_key_id: AKIAIZ4QVO3BCT6SJJVQ
  secret_access_key:
    secure: 2zC6n4KwuNKxX4iJlAPfMwfxTBKo1ykKA1hisOj+SFdBEzr1/3+WsJnJ9+Ro4DwLj1s6Ft+NWyQM8DOErUzW4XT2+q17TVcukRK02UYCfFUqogQrSu4QBvWKsHNSSOt3exA5vf7O3je+HZGh8cD3IdbnYQwYIpAhFW58AmvgOXzsXxulXht4rSWc45cTtahKluVJmSQgpQ3XNYFyWBL58BzXJ3zZkGXbWNwk308afIFkoub3YpIR9pra2RzC3FYYX/+XmZDqhpRBff6LiNcOyo93/5zmSCnntc6RIiXYMDcDSwIMdYqwYWkenEX4tT3unqNY6IT5oTg5nYGXMIg7j1ooNXD6sSLgZBzX2q7oiDZDuSITrspihFNUdmN1NUR+jVFC95rok+BoC+p376W11K5aHPNkkTaMMvEU9/c+z0eZMr8fYFDpfZQna9QkJQ4A5dGC1vsF9WZM2Aatswt2gUCI+fbmZSOyiJr0M+O5v5TTIXwSNKrOPoCua18e3xLpoka5krrwDHDErHGXx/rfGT2nk0CjgDkRa2wOmG19Grq3OkhC+rtKtnMkum2N1Trfh6eNSBrItsyVy50HbiiCzX06lPSJ7QXD4V3k9IH3nDan/8EC3yEvPpKFwQzYUAT8SwkODFlqbMR/vDEWDgRpqHZD2brp4qTFH4H9fnxG8fY=
  bucket: d2gwebui
  region: eu-central-1
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui
