language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  access_key_id: AKIAIK5IXECGIGW67N7A
  secret_access_key:
    secure: "VJp8T/1lGDkzkMGdsr2hjwXLaO10UW1JGzC2m6fgxIS5T6KoD98SeVPjDUMSz6v9O8NlRQcddwKF3/e95PkB0Bj6VDw0xE3DHruDh34NOS81iCjVB58J6OrfL5RP2pxqPIeLtbUPPyeIoLmx13h8WVtSv7QdRK3z3UxQH9b5XxKKlTDLmmix+SOdc9njPpae2JUSTvX7VzPD4R9EuKjtETDKhvVKZztvvUoIX3lOVkfcpdWKEZ3P1pvwJbj1jQ2GAIiQ+dQtK6//NM+vm6xU2IZsOeS2qW3u5qJU5CqBOPxuTbqQuJvC29JPQCgBzN6mCFSRlX5tLrwE+esIC3QEO0W3K1tTfcaKLX+TAPdOFnDsevreadAm0TC3PPZ8eRKAZaBfLNJqlXanXRAs4HGlvxVFle3StB82a/Tj46X2buS1uSs0+NozfUlk+CnZ2pZ7FeABjCr728masVwh3XhdbOMs2Aquh6NtTt+jReMu52976Abmuxtl4BkDp85ozUaSd+Smz4Vi1NQpsIgUh2RzqgkLucFzlW3DJjte9NRgg7hUMeeRxNvt+nfaNB3NlwHelvpOLM/WOSAMeUd02Bgd1WtxQlvSlfyrLXQvdqMoIM7F8cpUZaHb1nSjGc9ml7/ehV1Zhk4rFCTjtFvgTjdjD+XODU1zXh61WalbRR4TfeA="
  bucket: d2gwebui
  region: eu-central-1
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui