language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  access_key_id: AKIAIK5IXECGIGW67N7A
  secret_access_key:
    secure: Oysi54bX21J3oPRjoWcwh1AKdBK0Kmyg4cdzl7LquZN+1mvExCoB9hsoNbRDBKdIrDVUT03crqjWy8DLOua1muZCnXlgkhRm5CviXzkNSeKckdLqgbkFFKjUIizD/Co2P8g+MCoFmnIO8YLqEVQ+nwv5M0Vj1w1BSW03jiIa8nH411N8yDm0WUsN4hpkqM8hTgkERcNvxDMHB7E7fRuPAzTMPSdRiPlPQoIyIGuWwYiXjGYSdccjG3angYYm+o2Lip7blvl6mxDNIm0dHo/qCFObXUluTVTyxhJBhkYn2t84dpMPiuHqmsOy3YSIEmaOEBpXIp22tFCZYwcZR1i21EyXaN2GxWRHzBfrwyc2Jz3qKmIMwDttbRLAvUDPXVPJZ8hS2z0261819vMIn8nEpOI/qPxEOm/QdAU7I1qRekjFWUozkHuhb8cL0peOBbPn+k1BwteefOLk16hVpwlgfEPc87h9yMqnvG+fINTRItC7pcvNAq1xJZlFI/my1Cedfh+sR4N5opM15RtXtmwzapULm6Tb4fQYl4BmKUiv7DA/BTv5iZzW8yxkTVxFteq20QcB7VmHD72krXVEQu/fz/iN3r4huduli+bU7aKE24o6yQaRusj0FHKNjC0DsjIADL1X9UXZvgggSTOuVRAVfrhX8Schz0rWeTyXNh+yj3c=
  bucket: d2gwebui
  region: eu-central-1
  local-dir: public
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui
