language: node_js
node_js:
- 6.10.0
before_script:
- cd WebUI && npm install
script: npm run build:dev
deploy:
  provider: s3
  access_key_id: AKIAIK5IXECGIGW67N7A
  secret_access_key: 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
  bucket: d2gwebui
  region: eu-central-1
  local-dir: public
  acl: public_read
  skip_cleanup: true
  on:
    repo: AvoJFB/d2g-webui